### ISSUE TITLE
Clicking on results does not work (sometimes)

### ISSUE THREAD

**Issue by muan** [github/text-expander-element#1]
![](https://cl.ly/195bebc02985/Screen%252520Recording%2525202019-07-15%252520at%25252015.11.gif)

Pretty sure this is the culprit. 🤕 An easy fix would be to make this longer, but it'd be nice if it's not such a magic number.

https://github.com/github/text-expander-element/blob/0b969143e62e9753197815c32a5484fd51e521c5/src/text-expander-element.js#L113-L116

David and I opted for this solution against binding a `mouseup` listener on `document`. We probably still need it. See https://github.com/github/auto-complete-element/pull/23.

cc @github/web-systems-reviewers

**Comment by mislav** [comment]
Like with the auto-complete element, could the solution be to delay deactivating on blur while the mouse button is pressed?

I also agree that ideally we should avoid installing global handlers, but as you said, a single handler that tracks whether the mouse button is up and down might be required to avoid this bug.

**Comment by haacked** [comment]
Hiya! I'm playing around with this component for a personal project and this bug seems to still exist.

I'm running Chrome Version 75.0.3770.142 (Official Build) (64-bit) on Windows 10 and the mouse click bug seems to still exist.

I verified it by running the example provided in the repo: https://github.github.com/markdown-toolbar-element/examples/.

The bug also seems to exist on GitHub. When I click on a mention, emoji, or issue suggestion, nothing happens. The menu disappears and focus is brought back to the text editor, but the suggestion I clicked on is not added to the textarea. Fortunately, using keyboard selection still works! 👍

**Comment by muan** [comment]
@haacked 👋

The package upgrade hasn’t been merged in github.com. 

Can you provide a GIF to show what’s happening and also verify in devtools that the package version loaded is 0.1.1 instead of 0.1.0? 

(ps the link you provided was to markdown toolbar)

**Comment by haacked** [comment]
Whoops, I meant to link to the example in this repository's description: https://github.github.io/text-expander-element/examples/

**Comment by haacked** [comment]
Here's the demo using https://github.github.io/text-expander-element/examples/

![text-expander-demo](https://user-images.githubusercontent.com/19977/61597275-63a15280-abc3-11e9-963a-ad5241547c30.gif)
